<h2>What is Appdate?</h2>

<p>Software applications are spreading out quickly, these times. Anyone who lives
in the software business or depends upon it, then may have a problem: <em>how can I be sure I'm
be using the latest - and, presumibly, more secure and advanced version?</em></p>

<p>Giving the huge demand for new features and bug fixing - not to count the
security problem that may arise from time to time - software applications are
promptly updated, (sometime) even on a daily basis.</p>

<p>We offer an information "hub" where all those changes are tracked. We surf
the web for you, targetting an always growing set of application web sites,
and building a simple list.</p>

<p>This list is then served as an RSS feed, for you to add it to your preferred
RSS feed reader.</p>

<h2>How much does it cost?</h2>
<p>As far as Appdate remains in the <a href="/page/betanotes/">beta stage</a>,
everyone will be able to use the site at full potential. Soon or later, some
ads may be added to the site and/or to the feeds.</p>

<p>We are also planning to set up an annual subscription fee for "pro" accounts,
where more feature (and no ads) will be served.</p>

<h2>How it works?</h2>
<p>
The site itself is only the <em>frontend</em> for Appdate. 
But in the background, lot of <em>smart bots</em> regularly traverse
every tracked project's site and see if an update has been released.
</p>
<p>At the time of writing, there's no other way than to, literally, scrape
those web pages and search some regular patterns inside them. For this to happen
in a sufficiently reliable way, a bot has to be written for each site/project.</p>
<p>For the geekiest of you, those scripts are in Python and the site is <em>powered by</em>
the <a href="http://framework.zend.com">Zend Framework</a>.</p>

<p>This work is very time consuming and a little frustrating. We all hope that this approach
may scale :)</p>

<h2>Why don't you track ...?</h2>
<p>
Well, there are <em>hundreds</em> of interesting projects out there but, as stated before,
the process of adding a project is not as "plug'n'play" as you may think.
We are, for now, focusing on the projects <em>we</em> use (it's a start, don't you think?).
</p>
<p>May you need a project tracked, don't hesitate and use the feedback form to let us know.</p>

<p>The Appdate team</p>
