<h2>Some notes about being "beta"</h2>

<p>As far as this site is considered "beta quality", please note that:</p>
<ul class="bullets">
<li>every user has full access to the site features</li>
<li>there could be issues with the tracked project info (some property may be added, other may be removed)</li>
<li>some updates could not be catched (if the target project site has been redesigned, for example)</li>
<li>this <em>beta stage</em> will be used by us to track any problems, so  to give you a <em>stable</em> and reliable system in the near future
<li>we do not know when Appdate will be out of beta stage</li>
</ul>
<p>Please also take a minute to read the <a href="/page/about/">about section</a>.</p>
<p>The Appdate team</p>
