<h2>The Appdate Bot</h2>
<p>
This project (Appdate.it) tries to retrieve the latest version of some important software,
along with some other additional information (release notes, release date, download URL).
</p>

<p>
It uses some custom written "bots" that are run on a regular basis (once an hour, at the moment)
to go and scrape the target application website to gather its data.
</p>

<p>Please <a href="mailto:claudio.cicali@gmail.com">contact me</a> (or use the feedback form) if:</p>

<ul class="bullets">
  <li>you think that this use of your site is not legitimate (your application will be promptly removed from our list)</li>
  <li>you think that there's a better way to gather the info we are interested into</li>
  <li>you know am XML DTD or microformats that may help, avoiding this scraping :)</li>
</ul>

<p>Of course, I'll be very glad to know if your site is redesigned, so I may update your bot "logic".</p>

<p>While you're here you may be interested on reading the <a href="/page/about">abount page</a> of this project</p> 

<p>Thank you!</p>

<p>The Appdate team</p>
