<h2>Appdate ChangeLog</h2>

<h4>Version 0.9beta9 - 2011/08/28</h4>
<ul>
  <li>Now using Beautiful Soup for some projects</li>
  <li>Added CKEDitor</li>
  <li>Added VirtualBox</li>
  <li>Added Socket.io</li>
  <li>Added Node.JS</li>
</ul>
<hr>

<h4>Version 0.9beta8 - 2010/05/21</h4>
<ul>
  <li>Added Emacs</li>
  <li>Added Django</li>
</ul>
<hr>

<h4>Version 0.9beta7 - 2009/03/14</h4>
<ul>
  <li>Added OpenOffice</li>
</ul>
<hr>

<h4>Version 0.9beta6 - 2009/03/01</h4>
<ul>
  <li>Added MooTools</li>
</ul>
<hr>

<h4>Version 0.9beta5 - 2009/02/28</h4>
<ul>
  <li>Added PostgreSQL (8 and 7)</li>
  <li>Added Ruby (1.9 and 1.8)</li>
</ul>
<hr>

<h4>Version 0.9beta4 - 2009/02/27</h4>
<ul>
  <li>Added FlowPlayer</li>
  <li>Added Python (2 and 3)</li>
</ul>
<hr>
<h4>Version 0.9beta3 - 2009/02/17</h4>
<ul>
  <li>Added PHP</li>
  <li>Added Ruby on Rails</li>
</ul>
<hr>
<h4>Version 0.9beta2 - 2009/02/03</h4>
<ul>
  <li>Added Apache 2.0 and Apache 2.2</li>
</ul>
<hr>
<h4>Version 0.9beta1 - 2009/01/25</h4>
<ul>
  <li>First public release</li>
</ul>
