<h2>The shelf, or why you don't need to register - yet</h2>

<p>First things first: the shelf is simply a <em>container</em>
where you put the projects you're interested to track. Just click
on the checkbox near the project name to have it added or removed
from your shelf.</p>

<p>Once you have at least one project in the shelf, you can use
directly the RSS we create for you, just for the projects you have
selected. You'll find shelf RSS url just in the shelf's box itself.</p>

<p>But how do we know that <em>you are you</em>, and that this is your shelf?</p>

<p>We could have used the regular registration approach, where you
entered your name, your email, your password etc... You could then 
login and edit your profile/shelf as usual.</p>

<p>We decided to take a much simpler approach, for now, and eventually
go to the registration route one time in the future. We use a dead simple 
cookie based system to recognize you. Once you <em>open</em> your shelf, we 
send you a cookie (that never expires) with a uniquely generated ID - your 
shelf id, indeed.</p>

<p>No username, no password, nothing.</p> 

<p>There are, of course, some drawbacks; we assumed that the computer where
you read the feed is the same used to browse the Appdate site. And that could
not be the case... or you could have deleted your cookies, "loosing" the shelf. We think
that as far as the tracked project number remains quite low, we could take
the risk of having someone have to re-create his/her shelf.</p>

<p>Soon you'll be able to re-use your shelf id, even if you clean up
your cookies; remember, in fact, that the shelf id is appended on the shelf's
RSS URL.</p> 

<p>The Appdate team</p>
